version: '3.1'
services:
  db:
    image: postgres:14-bullseye
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    healthcheck:
      test: pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  setup:
    build:
      context: ./setup
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=$POSTGRES_USER
      - DB_PASSWORD=$POSTGRES_PASSWORD
      - DB_NAME=$POSTGRES_DB
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
