[tool.black]
line-length = 100

[tool.isort]
line_length = 100
multi_line_output = 3
force_grid_wrap = 0
include_trailing_comma = true
use_parentheses = true

[tool.mypy]
disallow_any_explicit = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
ignore_missing_imports = true
python_version = "3.10"
warn_unreachable = true
warn_unused_configs = true