FROM python:3.10-slim-bullseye

ENV PYTHONUNBUFFERED=1

RUN pip install --upgrade pip && \
    pip install pipenv

WORKDIR /app
ADD Pipfile .
ADD Pipfile.lock .
RUN pipenv install --system --deploy --dev

ADD . .
ENTRYPOINT ["uvicorn", "--reload", "app.main:app"]
